version: '3.7'
services:
    api:
        restart: always
        build:
            context: .
        ports:
            - 5000:5000
        volumes:
            - .:/var/www
        command: 'php -S 0.0.0.0:5000 -t /var/www/public'
