version: '3.7'
services:
  api:
    build:
      context: ./Dockerfile.production
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: 'php -S 0.0.0.0:5000 -t /app/public'